apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::211125615103:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-Wh4g7bzAAKPj
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::211125615103:user/Jaiishva
      username: Jaiishva
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-29T14:01:43Z"
  name: aws-auth
  namespace: kube-system
  uid: d96f9e38-a788-4656-b02c-f182746c5f70
